### ISSUE TITLE
Can't work in my system

### ISSUE THREAD

**Issue by asimovc** [RedsXDD/neopywal.nvim#3]
I cloned this repo and put in my `.config/nvim/pack/plugins/start/` and used the default [configuration](https://github.com/RedsXDD/neopywal.nvim#configuration) and i get the default colors of neovim without any theme even lualine is the default theme.

You need any log of me i be grateful to help i really like this project.

**Comment by RolfSievert** [comment]
I assume you activated the theme as well? I use Plug to install and it all works perfectly for me.
```lua
local neopywal = require("neopywal")
neopywal.setup()
vim.cmd.colorscheme("neopywal")
```

**Comment by RedsXDD** [comment]
Honestly i could not replicate the issue, it seems to work fine for me when i install the plugin on that exact same path and run `:colorscheme neopywal`.

And about lualine, honestly i couldn't even get lualine to load with that `~/.config/nvim/pack` method at all, so i am not sure how i am supposed to test it, but one thing you can try to do is changing the `theme` lualine option to `auto` instead of explicitly setting it to `neopywal`. That should make lualine try to load which ever theme is avaliable at the moment, and running `:colorscheme neopywal` should tell it to load that theme automatically.

```lua
```

**Comment by asimovc** [comment]
Sorry i just forget to add `vim.cmd.colorscheme("neopywal")` in the config
