### ISSUE TITLE
Can't install with rocks.nvim

### ISSUE THREAD

**Issue by 0ldude** [RedsXDD/neopywal.nvim#5]
I'm trying this new neovim package manager called [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) 
and it errors at the install stage.
The issue is with the missing tags/releases in this repo, 
because rocks.nvim requires a version string to be fed to it.
I don't mean to bother but I'm convinced that with 
github automatic releases action this could be solved.
Could you try and enable them?
Thx for your work

**Comment by RedsXDD** [comment]
Yes i am aware that not having github releases is an issue not only on rocks.nvim but also in many other plugin managers, and i plan to start using them as soon as possible.
The reason i didn't do it until now is that this plugin was still in a somewhat "beta" stage, i have been making many breaking changes because the plugin is not super utilized or anything in order to better structure the plugin code when i do make the first github release.
I should release the first version of it really soon however, since i already improved the structure of the README file and added the couple of features i wanted the plugin to have for the 1.0 release (like the colorscheme compiler which i added a couple commits ago). There's only one thing left so expect 1.0 to be released soon.

**Comment by RedsXDD** [comment]
Update: semantic versioning should be implemented now.
From what i tested everything seems to be working fine with lazy.nvim using versions for plugin updates. So i believe the plugin should also work now with rocks.nvim.
For now i will close this issue, but feel free to reopen it if you are still having any problems 🙂
